Password Hash and Token Generation added
codeIIEST/onlinejudge-server pull request #7
Opened 2020-11-19 03:06 UTC by arnabsen1729

- Password is hashed using `bcrypt` before storing in db
- Login verification added

2020-11-20 16:24 UTC, arnabsen1729 commented
@raydwaipayan  do check it out

2020-11-20 16:28 UTC, raydwaipayan requested changes

2020-11-20 16:28 UTC, raydwaipayan commented on docker-compose.yml
> +       - "127.0.0.1:5432:${DB_PORT}"
This is wrong.
In a bind, port1:port2,
port1 in your local system will be bound to port2 in
docker's internal network stack.

2020-11-20 16:28 UTC, raydwaipayan commented on server/handler/user_handler.go
> +		panic(err)
Don't panic in production.
Use log.Fatal(err) instead

2020-11-20 16:28 UTC, raydwaipayan commented on .gitignore
> +bin/
missing newline at end of file

2020-11-22 12:04 UTC, raydwaipayan approved these changes
LGTM

2020-11-22 12:04 UTC, merged